image: ruby:2.7.0

cache:
  paths:
    - vendor/bundle
    - node_modules

services:
  - postgres:11

variables:
  BUNDLE_PATH: vendor/bundle
  DISABLE_SPRING: 1
  DB_HOST: postgres

before_script:
  - bundle check || bundle install --jobs $(nproc)
  - bundle exec rails db:create RAILS_ENV=test
  - bundle exec rails db:schema:load RAILS_ENV=test

stages:
  - test
  - lint

Tests:
  stage: test
  script:
    - bundle exec rspec

Rubocop:
  stage: lint
  except:
    - master
  script:
    - bundle exec rubocop