default: &default
  adapter: postgresql
  port: 5432
  host: localhost
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: learn_japanese_pod_backend_development

test:
  <<: *default
  database: learn_japanese_pod_backend_test

production:
  <<: *default
  database: learn_japanese_pod_backend_production
  username: learn_japanese_pod_backend
  password: <%= ENV['LEARN_JAPANESE_POD_BACKEND_DATABASE_PASSWORD'] %>
